-- Realtime Publication Configuration (v1.0 Stable)
-- Publication: supabase_realtime

-- Tables added to publication (in order added):
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
ALTER PUBLICATION supabase_realtime ADD TABLE public.sessions;
ALTER PUBLICATION supabase_realtime ADD TABLE public.bookings;
ALTER PUBLICATION supabase_realtime ADD TABLE public.goals;
ALTER PUBLICATION supabase_realtime ADD TABLE public.tasks;
ALTER PUBLICATION supabase_realtime ADD TABLE public.student_progress;
ALTER PUBLICATION supabase_realtime ADD TABLE public.program_enrollments;
ALTER PUBLICATION supabase_realtime ADD TABLE public.shared_files;
ALTER PUBLICATION supabase_realtime ADD TABLE public.student_timeline_events;
ALTER PUBLICATION supabase_realtime ADD TABLE public.profiles;
ALTER PUBLICATION supabase_realtime ADD TABLE public.tags;
ALTER PUBLICATION supabase_realtime ADD TABLE public.student_tags;
ALTER PUBLICATION supabase_realtime ADD TABLE public.custom_forms;
ALTER PUBLICATION supabase_realtime ADD TABLE public.form_submissions;
ALTER PUBLICATION supabase_realtime ADD TABLE public.events;
ALTER PUBLICATION supabase_realtime ADD TABLE public.event_attendees;
ALTER PUBLICATION supabase_realtime ADD TABLE public.event_waitlist;
ALTER PUBLICATION supabase_realtime ADD TABLE public.event_activity;
ALTER PUBLICATION supabase_realtime ADD TABLE public.event_comments;
ALTER PUBLICATION supabase_realtime ADD TABLE public.event_speakers;
ALTER PUBLICATION supabase_realtime ADD TABLE public.event_feedbacks;
ALTER PUBLICATION supabase_realtime ADD TABLE public.event_files;
ALTER PUBLICATION supabase_realtime ADD TABLE public.event_notifications;
ALTER PUBLICATION supabase_realtime ADD TABLE public.event_recordings;
ALTER PUBLICATION supabase_realtime ADD TABLE public.resources;
ALTER PUBLICATION supabase_realtime ADD TABLE public.resource_categories;
ALTER PUBLICATION supabase_realtime ADD TABLE public.resource_tags;
ALTER PUBLICATION supabase_realtime ADD TABLE public.resource_assignments;
ALTER PUBLICATION supabase_realtime ADD TABLE public.resource_favorites;
ALTER PUBLICATION supabase_realtime ADD TABLE public.resource_comments;
ALTER PUBLICATION supabase_realtime ADD TABLE public.resource_activity;
ALTER PUBLICATION supabase_realtime ADD TABLE public.resource_completions;
ALTER PUBLICATION supabase_realtime ADD TABLE public.recently_viewed;
ALTER PUBLICATION supabase_realtime ADD TABLE public.reviews;
ALTER PUBLICATION supabase_realtime ADD TABLE public.review_history;
ALTER PUBLICATION supabase_realtime ADD TABLE public.visitor_bookings;
ALTER PUBLICATION supabase_realtime ADD TABLE public.booking_notes;
ALTER PUBLICATION supabase_realtime ADD TABLE public.booking_timeline;
ALTER PUBLICATION supabase_realtime ADD TABLE public.gallery_items;
ALTER PUBLICATION supabase_realtime ADD TABLE public.social_links;
ALTER PUBLICATION supabase_realtime ADD TABLE public.website_settings;
ALTER PUBLICATION supabase_realtime ADD TABLE public.form_assignments;
