import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './e2e',
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 4 : 2,
  reporter: [
    ['html', { outputFolder: 'playwright-report' }],
    ['junit', { outputFile: 'playwright-report/results.xml' }],
    ['json', { outputFile: 'playwright-report/results.json' }],
    ['list'],
  ],
  use: {
    baseURL: 'https://today-ten-zeta.vercel.app',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'on-first-retry',
    actionTimeout: 15000,
    navigationTimeout: 30000,
  },
  projects: [
    {
      name: 'setup',
      testMatch: /.*\.setup\.ts/,
    },
    {
      name: 'chromium-visitor',
      dependencies: [],
      use: { ...devices['Desktop Chrome'] },
      testMatch: /visitor-flow\.spec\.ts/,
    },
    {
      name: 'chromium-mentor',
      dependencies: ['setup'],
      use: { ...devices['Desktop Chrome'] },
      testMatch: /mentor-flow\.spec\.ts/,
    },
    {
      name: 'chromium-student1',
      dependencies: ['setup'],
      use: { ...devices['Desktop Chrome'] },
      testMatch: /student-flow\.spec\.ts/,
    },
    {
      name: 'chromium-realtime',
      dependencies: ['setup'],
      use: { ...devices['Desktop Chrome'] },
      testMatch: /realtime\.spec\.ts/,
    },
    {
      name: 'chromium',
      dependencies: ['setup'],
      use: { ...devices['Desktop Chrome'] },
      testIgnore: [
        /visitor-flow\.spec\.ts/,
        /mentor-flow\.spec\.ts/,
        /student-flow\.spec\.ts/,
        /student-isolation\.spec\.ts/,
        /realtime\.spec\.ts/,
        /student-dashboard\.spec\.ts/,
        /debug-auth\.spec\.ts/,
      ],
    },
    {
      name: 'firefox',
      dependencies: ['setup'],
      use: { ...devices['Desktop Firefox'] },
      testIgnore: [
        /visitor-flow\.spec\.ts/,
        /mentor-flow\.spec\.ts/,
        /student-flow\.spec\.ts/,
        /student-isolation\.spec\.ts/,
        /realtime\.spec\.ts/,
        /student-dashboard\.spec\.ts/,
        /debug-auth\.spec\.ts/,
      ],
    },
    {
      name: 'webkit',
      dependencies: ['setup'],
      use: { ...devices['Desktop Safari'] },
      testIgnore: [
        /visitor-flow\.spec\.ts/,
        /mentor-flow\.spec\.ts/,
        /student-flow\.spec\.ts/,
        /student-isolation\.spec\.ts/,
        /realtime\.spec\.ts/,
        /student-dashboard\.spec\.ts/,
        /debug-auth\.spec\.ts/,
      ],
    },
    {
      name: 'mobile-chrome',
      dependencies: ['setup'],
      use: { ...devices['Pixel 9'] },
      testIgnore: [
        /visitor-flow\.spec\.ts/,
        /mentor-flow\.spec\.ts/,
        /student-flow\.spec\.ts/,
        /student-isolation\.spec\.ts/,
        /realtime\.spec\.ts/,
        /student-dashboard\.spec\.ts/,
        /debug-auth\.spec\.ts/,
      ],
    },
    {
      name: 'mobile-safari',
      dependencies: ['setup'],
      use: { ...devices['iPhone 16'] },
      testIgnore: [
        /visitor-flow\.spec\.ts/,
        /mentor-flow\.spec\.ts/,
        /student-flow\.spec\.ts/,
        /student-isolation\.spec\.ts/,
        /realtime\.spec\.ts/,
        /student-dashboard\.spec\.ts/,
        /debug-auth\.spec\.ts/,
      ],
    },
  ],

})
